[package]
name = "example"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
hedge_rs = { path = "../hedge" }
env_logger = { workspace = true }
log = { workspace = true }
ctrlc = { workspace = true }
anyhow = { workspace = true }
rustls = { workspace = true }
